name: CI

on:
  [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: sudo apt install clang-tidy

    - name: Init build
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
    
    - name: Test
      run: ctest
      working-directory: ./build
