name: CI

on:
  [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: | 
        sudo apt update
        sudo apt install clang-tidy gcovr

    - name: Init build
      run: cmake -S . -B build -D CODE_COVERAGE=ON
    
    - name: Upload build init files
      uses: actions/upload-artifact@v2
      with:
        name: init-build-folder
        path: ./build

    - name: Build
      run: cmake --build build
    
    - name: Test
      run: ctest
      working-directory: ./build

    - name: Generate coverage report
      run: gcovr build/ --xml -o coverage.xml

    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true 
  
  check-format:
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: sudo apt install clang-format-9 --yes

    - name: Download build init files
      uses: actions/download-artifact@v2
      with:
        name: init-build-folder
        path: ./build

    - name: Clang-format 
      run: make check-format 
      working-directory: ./build

