name: CI

on:
  [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: | 
        sudo apt update
        sudo apt install clang-tidy clang-format-9 gcovr --yes

    - name: Init build
      run: cmake -S . -B build -D CODE_COVERAGE=ON

    - name: Build
      run: cmake --build build
    
    - name: Test
      run: ctest
      working-directory: ./build

    - name: Clang-format 
      run: make check-format 
      working-directory: ./build

    - name: Generate coverage report
      run: gcovr build/ --xml -o coverage.xml

    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true 
