name: clang-format

on: 
  [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: | 
        sudo apt update
        sudo apt install clang-format-9 --yes
        clang-format --version
    
    - name: Init build
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
    
    - name: Check Format
      run: make check-format 
      working-directory: ./build