name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
    
    - name: Test
      run: ctest
      working-directory: ./build
