name: Static analysis

on:
  schedule:
    # https://crontab.guru/#0_10_*/2_*_*
    # At 10:00 every two days.
    - cron: '0 10 */2 * *'

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: sudo apt install clang-tools

    - name: Init build
      run: scan-build cmake -S . -B build-scan

    - name: Build
      run: scan-build -o build-scan/scan-result cmake --build build-scan

    - name: Check if there is errors or warnings
      # When the static analysis is successful, the `scan-result` directory is empty.
      run: '[ -z "$(ls -A build-scan/scan-result)" ]'
